name: Docker Image CI

on:
  push:
  schedule:
    - cron: "0 */12 * * *"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: zenato/docker-action@master
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tkti/archlinux
          tag: latest
