name: Docker Image CI Push

on:
  push:
  schedule:
    - cron: "0 0 * * 1"
jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: zenato/docker-action@master
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tkit1994/archlinux
          tag: latest
